name: add to project g2 python

on:
  issues:
    types:
      - opened
      - reopened

permissions:
  repository-projects: write

jobs:
  add-to-project:
    secrets:
      SENZING_GITHUB_PROJECT_RW_TOKEN: ${{ secrets.SENZING_GITHUB_PROJECT_RW_TOKEN }}
    uses: senzing-factory/build-resources/.github/workflows/add-to-project.yaml@v1
    with:
      classic: false
      project-number: ${{ vars.SENZING_PROJECT_G2_PYTHON }}
      org: ${{ vars.SENZING_GITHUB_ACCOUNT_NAME }}
